### ISSUE TITLE
Add padding string/number pipes

### ISSUE THREAD

**Issue by spyr0s** [danrevah/ng-pipes#10]
I think padLeft, padRight pipes would be useful for string or for formatting numbers like 0003, 02 etc

**Comment by danrevah** [comment]
I agree.. let me find a time to add those pipes. 
you are also welcome to make a pull-request with those pipes.

**Comment by spyr0s** [comment]
Thanks, I'll send you a pull request in the following days

**Comment by spyr0s** [comment]
I opened a pull request to next branch (although there are some other commits along mine)
https://github.com/danrevah/ng-pipes/pull/11/files

**Comment by danrevah** [comment]
Looks good to me.. Thanks!
I'll be merging this into master and releasing it to version `1.1.0` soon.
