### ISSUE TITLE
Shouldn't the package name be `ng-pipes`?

### ISSUE THREAD

**Issue by umayr** [danrevah/ng-pipes#9]
Shouldn't the package name be `ng-pipes`? As Igor said in his [tweet](https://twitter.com/IgorMinar/status/807564558986514432):
> ... but please don't call projects ng2- or angular2-, etc.

There's already a package named by `ng-pipes` but this could be published with scoping.

**Comment by danrevah** [comment]
You are right. 
I've noticed this tweet few days ago, and I've just renamed the repository to `ng-pipes`.
The npm package will also be renamed soon.

**Comment by danrevah** [comment]
npm package is now named `ngx-pipes` after the `ngx` convention.
